### ISSUE TITLE
Not working with German Timeformat

### ISSUE THREAD

**Issue by Knightmore** [yschuurmans/FFXIVMoneyTracker#2]
DateTime is saved as dd.MM.yyyy in de-DE Culture and throws a conversion error like this:
![2022-04-18 14_43_21-FINAL FANTASY XIV](https://user-images.githubusercontent.com/35805408/163810140-a4778013-7107-4e69-b78b-004801e3af64.png)

You added CultureInfo.InvariantCulture to the FromFileLine() function but forgot about it in ToFileLine() in MoneyTransactions (Line 23);

return $"{TimeStamp.ToString("dd/MM/yyyy HH:mm:ss", CultureInfo.InvariantCulture)};{Total};{Change}";

**Comment by yschuurmans** [comment]
If it is as simple as adding CultureInfo.InvariantCulture, it should be fixed now. You might need to delete your config file existing in XIVLauncher\pluginConfigs\XIVMoneyTracker though..

**Comment by Knightmore** [comment]
Yeah, that did it. It's working now.
