### ISSUE TITLE
Date/Time Fortmat is causing problems

### ISSUE THREAD

**Issue by ArkfrostLumas** [yschuurmans/FFXIVMoneyTracker#3]
The plugin is simply not opening the Money Tracker window, neither when I press on the settings wheel in the xlplugins window, nor when I use /mtrack.

The dalamud log gives me this error message:

> 2022-05-19 18:33:50.284 +02:00 [ERR] Error while dispatching command /mtrack (Argument: )
> System.FormatException: String '24.02.2022 22:09:05' was not recognized as a valid DateTime.
>    at System.DateTimeParse.ParseExact(ReadOnlySpan`1 s, ReadOnlySpan`1 format, DateTimeFormatInfo dtfi, DateTimeStyles style)
>    at System.DateTime.ParseExact(String s, String format, IFormatProvider provider, DateTimeStyles style)
>    at FFXIVMoneyTracker.Models.MoneyTransaction.FromFileLine(String line) in  D:\Git\FFXIVMoneyTracker\XIVMoneyTracker\Models\MoneyTransaction.cs:line 28
>    at FFXIVMoneyTracker.Models.CharacterModel.LoadAllTransactions() in D:\Git\FFXIVMoneyTracker\XIVMoneyTracker\Models\CharacterModel.cs:line 58
>    at FFXIVMoneyTracker.Plugin.OnCommand(String command, String args) in D:\Git\FFXIVMoneyTracker\XIVMoneyTracker\Plugin.cs:line 173
>    at Dalamud.Game.Command.CommandManager.DispatchCommand(String command, String argument, CommandInfo info) in  C:\goatsoft\companysecrets\dalamud\Game\Command\CommandManager.cs:line 117
> 2022-05-19 18:33:50.284 +02:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wNS0xOVQxODozMzo1MC4yODQ3MzMrMDI6MDAiLCJJbmZvIjoiU3lzdGVtLkZvcm1hdEV4Y2VwdGlvbjogU3RyaW5nICcyNC4wMi4yMDIyIDIyOjA5OjA1JyB3YXMgbm90IHJlY29nbml6ZWQgYXMgYSB2YWxpZCBEYXRlVGltZS5cclxuICAgYXQgU3lzdGVtLkRhdGVUaW1lUGFyc2UuUGFyc2VFeGFjdChSZWFkT25seVNwYW5gMSBzLCBSZWFkT25seVNwYW5gMSBmb3JtYXQsIERhdGVUaW1lRm9ybWF0SW5mbyBkdGZpLCBEYXRlVGltZVN0eWxlcyBzdHlsZSlcclxuICAgYXQgU3lzdGVtLkRhdGVUaW1lLlBhcnNlRXhhY3QoU3RyaW5nIHMsIFN0cmluZyBmb3JtYXQsIElGb3JtYXRQcm92aWRlciBwcm92aWRlciwgRGF0ZVRpbWVTdHlsZXMgc3R5bGUpXHJcbiAgIGF0IEZGWElWTW9uZXlUcmFja2VyLk1vZGVscy5Nb25leVRyYW5zYWN0aW9uLkZyb21GaWxlTGluZShTdHJpbmcgbGluZSkgaW4gRDpcXEdpdFxcRkZYSVZNb25leVRyYWNrZXJcXFhJVk1vbmV5VHJhY2tlclxcTW9kZWxzXFxNb25leVRyYW5zYWN0aW9uLmNzOmxpbmUgMjhcclxuICAgYXQgRkZYSVZNb25leVRyYWNrZXIuTW9kZWxzLkNoYXJhY3Rlck1vZGVsLkxvYWRBbGxUcmFuc2FjdGlvbnMoKSBpbiBEOlxcR2l0XFxGRlhJVk1vbmV5VHJhY2tlclxcWElWTW9uZXlUcmFja2VyXFxNb2RlbHNcXENoYXJhY3Rlck1vZGVsLmNzOmxpbmUgNThcclxuICAgYXQgRkZYSVZ> Nb25leVRyYWNrZXIuUGx1Z2luLk9uQ29tbWFuZChTdHJpbmcgY29tbWFuZCwgU3RyaW5nIGFyZ3MpIGluIEQ6XFxHaXRcXEZGWElWTW9uZXlUcmFja2VyXFxYSVZNb25leVRyYWNrZXJcXFBsdWdpbi5jczpsaW5lIDE3M1xyXG4gICBhdCBEYWxhbXVkLkdhbWUuQ29tbWFuZC5Db21tYW5kTWFuYWdlci5EaXNwYXRjaENvbW1hbmQoU3RyaW5nIGNvbW1hbmQsIFN0cmluZyBhcmd1bWVudCwgQ29tbWFuZEluZm8gaW5mbykgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcR2FtZVxcQ29tbWFuZFxcQ29tbWFuZE1hbmFnZXIuY3M6bGluZSAxMTciLCJDb250ZXh0IjoiRXJyb3Igd2hpbGUgZGlzcGF0Y2hpbmcgY29tbWFuZCBcIi9tdHJhY2tcIiAoQXJndW1lbnQ6IFwiXCIpIn0=

So apparently the date & time format is causing the problem. I've seen there was a commit recently "maybe fix regional time format", so I'm not sure if this is something you want to fix or already tried to fix (in the latter case it didn't work yet).

Anyways, thanks for making this plugin, since I've been waiting for something like that in quite a while :)

**Comment by yschuurmans** [comment]
How long have you been using this plugin? This seems like quite an old `MoneyTransaction` log line, is it maybe possible that you used it once before I fixed the regional time formats?

**Comment by ArkfrostLumas** [comment]
I've got it installed for a couple of months now, and always updated it whenever there was an update. It also says it's on the version with the change log "maybe fix regional formatting".

I guess I'll try uninstalling it and removing it from %appdata% as well and reinstalling it. Maybe that fixes it then

**Comment by yschuurmans** [comment]
Strange situation, since that error _does_ seem to indicate a log from the 24th of February. This issue is a recent one I presume? 
Given the error above, and the fact that you have been using this addon for a while now, you should never have been able to open the window as far as I can tell 😂 

Could you maybe send me the contents of the transactionlog file at: `%appdata%\XIVLauncher\pluginConfigs\XIVMoneyTracker\[Your Charactername].txt`?

**Comment by ArkfrostLumas** [comment]
> you should never have been able to open the window as far as I can tell 😂

Yeah, I never could xD
I just left it installed in hopes it would get fixed eventually ^^'

It's working now by the way. All I had to do was to uninstall it and delete both its files in installedPlugins and pluginConfig and reinstall it. Then it worked :)

**Comment by yschuurmans** [comment]
> It's working now by the way. All I had to do was to uninstall it and delete both its files in installedPlugins and pluginConfig and reinstall it. Then it worked :)

Ahh yeah that makes sense, you don't happen to still have the original file do you? I would be able to fix it up for you if you want. 

As a side note; how did you actually manage to find this plugin in the first place? I have not publicly posted this one somewhere as far as I know, but it has been discovered by quite a few people at this point 😅

**Comment by ArkfrostLumas** [comment]
Nope, I don't have it anymore, but since it's working now it's no problem
And I found the plugin via the Dalamud Repo Browser plugin from UnknownX :D 

![image](https://user-images.githubusercontent.com/39298126/169789770-b22db4a7-a9ff-4c86-a251-048121fd32be.png)

**Comment by yschuurmans** [comment]
That does explain a lot, I was wondering how so many random people managed to find their way to this page 😂 

At least I'm glad that it works for you now!
