### ISSUE TITLE
Suggestion: Daily Graph

### ISSUE THREAD

**Issue by ArkfrostLumas** [yschuurmans/FFXIVMoneyTracker#4]
Hey there again. 
Just an idea I had that you might consider implementing whenever you're in the mood, have time and want to do that. Would be cool to have some kind of graph that shows your balance and changes to it. Something like this:

![image](https://user-images.githubusercontent.com/39298126/171595274-31bd86b6-791e-430f-85ae-c9a360372274.png)

Kinda like WoW's TradeSkillMaster graph:

![image](https://user-images.githubusercontent.com/39298126/171595367-7a74517f-1df6-4978-bfc9-e3e0e9888fcf.png)

Would be really cool to have something like that, but if that's too troublesome I can understand if you don't wanna do that x)

**Comment by yschuurmans** [comment]
While I would like to do this (TSM is actually the original inspiration of this plugin hehe), it is quite hard to do properly. So yes this is somewhere on my backlog, but don't expect it soon.

**Comment by ArkfrostLumas** [comment]
Oh, that's really cool to read.
Yeah, I don't expect it to be done soon, but if it's on the bucket list of features I'm already totally happy :D
