### ISSUE TITLE
Suggestion : Flip the dates option

### ISSUE THREAD

**Issue by 4Donic** [yschuurmans/FFXIVMoneyTracker#5]
So that the newest expenses/Gains are on top and not on the bottom

**Comment by yschuurmans** [comment]
Yeah good idea

**Comment by yschuurmans** [comment]
Implemented it as a new toggle next to the export button.
![image](https://user-images.githubusercontent.com/1494661/171913686-dd97db9a-c71f-4a41-99de-f20449b7d691.png)
